- build.gradle.kts
Previous refactor to support building with/without BuildKit introduced an bug where dependency linking between tasks when building with BuildKit was no longer performed.
> Fix build dependencies when building with BuildKit.

- cantaloupe/rootfs/etc/confd/templates/cantaloupe.properties.tmpl
- cantaloupe/rootfs/etc/confd/templates/setenv.sh.tmpl
- docker-compose.yml
- sandbox/Dockerfile
- sandbox/rootfs/etc/confd/templates/sandbox-setup.sh.tmpl
- Updates cantaloupe.properties to work with Cantaloupe ^4.0
- Configures tomcat to allow url encoded slashes for Cantaloupe
- Exposes Cantaloupe at drupal.localhost/cantaloupe instead of cantaloupe.localhost to dance around CORS
- Enables the traefik dashboard for debugging
- Pulls down latest openseadragon in Dockerfile
- Deploys it in the startup script since its location is on a bind mount
- Make a Repository Item and give it a display hint of "Openseadragon"
- Give it an Image media tagged as Original File
- Go view the node and you should have an OSD viewer with zoom/scroll
I can't seem to upload tiffs appropriately.  This doesn't have anything to do with cantaloupe as far as I can tell.  I can upload it in the widget in Drupal, but after I save the form, a File entity is created …
> Openseadragon working with cantaloupe 4

- .gitattributes
- .gitignore
- activemq/Dockerfile
- base/Dockerfile
- base/build/download.sh
- base/rootfs/usr/local/bin/git-clone-cached.sh
- blazegraph/Dockerfile
- build.gradle.kts
- cantaloupe/Dockerfile
- composer/Dockerfile
- crayfish/Dockerfile
- crayfits/Dockerfile
- fcrepo/Dockerfile
- fits/Dockerfile
- java/rootfs/usr/local/bin/install-apache-service.sh
- karaf/Dockerfile
- matomo/Dockerfile
- sandbox/Dockerfile
- solr/Dockerfile
- tomcat/Dockerfile
- tomcat/rootfs/usr/local/bin/install-war-into-tomcat.sh
Should address the issue: https://github.com/Islandora-Devops/isle-buildkit/issues/21
Address two issues:
- Previously Windows EOL characters were used in some files not covered by .gitattributes.
- Previously download files that did not download successfully would pollute the build cache.
Solutions:
- Change .gitattributes so the appropriate files have the appropriate line endings.
- For all download files check against a known checksum, if check fails remove the file from the build cache so it can be downloaded again.
> Build issues on Windows 

- sandbox/Dockerfile
- sandbox/rootfs/etc/confd/templates/sandbox-setup.sh.tmpl
Should be no change in functionality after this PR.  It just deploys it all in the Dockerfile.  Which initially didn't work for me, b/c you'll need to delete your drupal volume for this to work.  If you don't delete your volume and already have one, it will _not_ deploy properly.
> Deploying openseadragon in dockerfile and not init script

- fcrepo/rootfs/etc/cont-init.d/03-fcrepo-setup.sh
Allows container to write to bind mounted data folder when first created.
> Allow for bind mounting Fedora data directory.

- nginx/Dockerfile
Missing dependency required for running 7x migrate module.
> Include ext xsl

- activemq/rootfs/etc/confd/conf.d/jetty-realm.properties.toml
- alpaca/rootfs/etc/confd/templates/org.fcrepo.camel.service.cfg.tmpl
- drupal/rootfs/etc/confd/templates/setup-environment.sh.tmpl
- fcrepo/README.md
- fcrepo/rootfs/etc/confd/templates/activemq.xml.tmpl
- matomo/rootfs/etc/confd/templates/setup-environment.sh.tmpl
Before this change the defaults were being used as the environment variables were being ignored
> Fixes configuration to match documentation and actually work.

- nginx/Dockerfile
We've added it in a custom image for our work, but it'd be nice and clean to add it here. BAM is pretty widely used, so I don't think it's too much overhead to add.
> Backup And Migrate requires MYSQLI

- cantaloupe/Dockerfile
- cantaloupe/rootfs/etc/confd/templates/cantaloupe.properties.tmpl
Had an issue where in cantaloupe tried to use Kakadu even though it wasn't installed so switched selection to manual. Also made sure that OpenJPEG tools were installed so they could be used appropriately. I think previous calls must have been using the ImageMagick JPEG2000 delegate which is a bit slower. See docs: https://cantaloupe-project.github.io/manual/4.1/images.html
Can test the existing implementation vs the changes against the attached JP2. Prior to this pull request it does not render, afterwards it does.
[Sample.zip](https://github.com/Islandora-Devops/isle-buildkit/files/5218114/Sample.zip)
> Fixes display issues with some JP2 images.

- drupal/rootfs/usr/share/drush/Commands/UpdateSettingsCommands.php
Adds a function which can be used by downstream developers to specify the trusted host settings on a per-site basis.
> Add function for writing trusted hosts to settings file.

- drupal/rootfs/etc/islandora/utilities.sh
Support waiting for specified services, which is useful when optional services like `fcrepo` and `blazegraph` aren't used.  Otherwise, `wait_for_service` will timeout.
> Allow parameterization of wait_for_service function

- drupal/Dockerfile
Adds GNU `patch` to the Drupal container in order to support the use of `composer-patches`, and attempts to follow the existing pattern/usage of buildkit directives.  I can revise the PR if you prefer this to occur in a different image, or if you want to incorporate the commands into a single layer, just LMK.
https://github.com/cweagans/composer-patches is a module which allows for local patches to be applied to vendored code required by `composer.json`.  Johns Hopkins uses `composer-patches` to apply local patches to SimpleSAMLphp.  The version of `patch` present on the alpine image isn't compatible with `composer-patches`, thus the need for this PR.
> Add GNU patch for use with composer-patches.

- tomcat/rootfs/etc/confd/conf.d/tomcat-users.toml
The tomcat users file wasn't getting templated out with roles for the admin user.  I needed to spin up a fedora with basic auth instead of syn in order to use the fcrepo-import-export tool, and bumped into this. Turned out to just be missing a key in the .toml file for the template.
> Missing key for /tomcat/admin/roles

- build.gradle.kts
- gradle.properties
Use the output of `git describe` to tag images when the `version` property is absent or the empty string.  It uses the [com.palantir.git-version plugin](https://github.com/palantir/gradle-git-version) to generate a string based on the output of `git describe --tags --always --first-parent`
This PR relies on the existing premise/assumption that the Gradle's project version is used as a Docker image tag.  It maintains backwards compatibility with version 0.0.1 of the plugin: if a `version` property is specified, it will be used.  If a version property is _not_ specified (absent or the empty string), the output of `git describe` is used as the version.
As a consequence, there will _always_ be a value for `version`, therefore a Docker tag will always be generated based on the project version. …
> Version Docker images using `git describe` when no `version` is specified

- drupal/rootfs/etc/confd/templates/setup-environment.sh.tmpl
- drupal/rootfs/etc/cont-init.d/00-update-reverse-proxy-ip.sh
- drupal/rootfs/etc/islandora/utilities.sh
- drupal/rootfs/usr/share/drush/Commands/UpdateSettingsCommands.php
I've managed to get the https situation sorted out a bit better, and this lets us properly configure drupal for a reverse proxy setup.  In order to make things work before it needed to be misconfgured on purpose, so this is a bit of an improvement :sweat_smile: 
If you're not using Traefik, you have to provide the IP(s) of the reverse proxy to Drupal via `DRUPAL_REVERSE_PROXY_IPS` using a comma separated list of IPs.  If you are using Traefik, it will try and auto-detect it generate the variable for you to save a step.
In order to actually set the settings, there's a new drush command, `islandora:settings:set-reverse-proxy`
You'll need this for an upcoming `isle-dc` PR and can test it with that.
> Injecting DRUPAL_REVERSE_PROXY_IP for traefik if it's available

- nginx/rootfs/etc/confd/templates/php-fpm.conf.tmpl
- nginx/rootfs/etc/confd/templates/www.conf.tmpl
- nginx/rootfs/etc/services.d/fpm/run
This doesn't really change anything functionally in this container but allows for downstream containers to run multiple `php-fpm` services if needed. 
One may want to run multiple `php-fpm` services so they can include/exclude `php` extensions like `xdebug` dynamically. In this scenario two `php-fpm` services are running one with `xdebug` loaded and the other without.    
`nginx` then looks at the cookies of requests, if it finds a `XDEBUG_SESSION` cookie it forwards the request on the the `php-fpm` socket/service which has `xdebug` **enabled** otherwise it passes the request to the `php-fpm` socket/service with `xdebug` **disabled**. 
Why would one do this? `xdebug` really kills performance and can cause failures due to timeouts even when not running, just by having the module enabled …
> Allow for multiple php-fpm services to be run in downstream containers.

- drupal/rootfs/etc/islandora/utilities.sh
- drupal/rootfs/etc/nginx/conf.d/default.conf
When loading certain pages that are packed with heavy content/LONG headers nginx crashes with a 502 error, this specially true when trying to edit nodes
https://vander.host/knowledgebase/web-servers/502-bad-gateway-upstream-sent-too-big-header-while-reading-response-header-from-upstream-on-hosted-nginx-website/
this patch fixes that and also forces SSL on ALL resources
> Adding proxybuffer updates to prevent 502 errors, also enable SSL by default always

- .github/workflows/release.yml
- build.gradle.kts
- gradle.properties
Using the git tag for the docker image when a new release is minted.
Should be merged along with https://github.com/Islandora-Devops/isle-gradle-docker-plugin/pull/3 after which using the release feature of GitHub should automatically build and publish docker images using the same tag string as the release. Will be tagged and pushed via GitHub actions.
> Automatically build / publish to DockerHub

- build.gradle.kts
- gradle.properties
Merge after https://github.com/Islandora-Devops/isle-gradle-docker-plugin/pull/6
Improves stability/speed of the builds in some cases and fixes some bugs.
> Bumped version of Gradle docker plugin and enabled caching

- mariadb/Dockerfile
- mariadb/README.md
- mariadb/rootfs/etc/cont-init.d/00-container-environment-01-set-root-user.sh
- mariadb/rootfs/etc/cont-init.d/03-mysql-setup.sh
- postgresql/Dockerfile
- postgresql/README.md
- postgresql/rootfs/etc/cont-init.d/00-container-environment-01-set-root-user.sh
- postgresql/rootfs/etc/cont-init.d/03-postgresql-setup.sh
Addresses https://github.com/Islandora-Devops/isle-buildkit/issues/126
To test first build then run the following:
```bash
docker run -d --rm -p 3306:3306  --name mysql local/mariadb
mysql --host 0.0.0.0 --port 3306 --protocol tcp --user root -p 
docker rm -f mysql
```
```bash
docker run -d --rm -p 3306:3306 -e DB_ROOT_PASSWORD=dbroot --name mysql local/mariadb
mysql --host 0.0.0.0 --port 3306 --protocol tcp --user root -p 
docker rm -f mysql
```
```bash
docker run -d --rm -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mysqlroot --name mysql local/mariadb
mysql --host 0.0.0.0 --port 3306 --protocol tcp --user root -p 
docker rm -f mysql
```
> Fix to use the right environment variables for database root user.

- download/Dockerfile
Useful when patching downloaded artefacts.
> Include patch in download image.

- composer/Dockerfile
Github has release a new format for personal access tokens.
https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/
Causing a failure to authenticate bugs:
https://github.com/composer/composer/issues/9820
Which was fixed in release 2.0.12:
https://github.com/composer/composer/commit/dc83ba93f3d8a35629f9a387632e8cd373a144d0
> Upgrade composer from 2.0.4 to 2.0.12

- fits/rootfs/etc/confd/conf.d/fits-service.properties.toml
An error in the confd toml file for the `fits-services.properties` file renders confd-related environment vars impotent.
1. Run any tagged version of the `fits` image, setting a documented environment variable for the fits service, being sure to allow time for the fits webapp to start:
```shell
docker run --rm -e FITS_MAX_IN_MEMORY_FILE_SIZE=10 <your_repo>/fits
``` 
Note that the output will show _default values for all environment variables_.  We expect " Max in-memory file size" to be `10`, not `4`:
```
2021-06-24 04:28:29 -  INFO - FitsServlet:143 - Max objects in object pool: 5 -- Max file upload size: 2000MB -- Max request object size: 2000MB -- Max in-memory file size: 4MB
```
2. Build the fits image from this PR (`./gradlew -Plocal build:fits`) and run the same command, but use the …
> correct fits-service.properties typo in confd toml.

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle.kts
Can now perform build scans with `--scan` argument.
Ideally this should be merged first: https://github.com/Islandora-Devops/isle-gradle-docker-plugin/pull/11
> Updated plugin / gradle to latest

- fcrepo6/Dockerfile
You can test this by setting `TAG=7b0461e91fc8c0fea6b32be6b3912103e6f77997` in your .env.  Everything should pretty much work the same.  Since we did testing on the previous RC, there isn't a ton that needs to be looked at other than basic sanity checks.
> Updating to fcrepo 6.0.0

- crayfish/Dockerfile
Updates Crayfish to the latest release. A full tagged release of isle-buildkit is probably in order after this making perhaps alpha 11 that isle-dc can then be updated to use.
> Bumped Crayfish to 2.0.0 release

- README.md
Proposing wording that explains Docker Hub's role in bridging Buildkit and Isle-DC.
Thanks to @adam-vessey and @noahwsmith for answering my question on [Slack](https://islandora.slack.com/archives/C01G5BKS96J/p1639422012114100).
> Explain how Docker Hub factors in the workflow.

- demo/Dockerfile
Code can change when pulling from a master branch, which causes checksum
checks to fail.
This can changes master to instead refer to explicit commits hashes.
The output docker images is byte for byte the same though.
> [issue-172] Use explicit commits in URLs such that

- nginx/Dockerfile
Allows downstream use of ldap php extension.
Address https://github.com/Islandora-Devops/isle-buildkit/issues/180
> Added LDAP extension to nginx/php image.

- drupal/rootfs/etc/islandora/utilities.sh
For some reason my islandora instance had some conflicting request handlers and dispatchers defined in the SOLR Server (search api).  It was difficult to discover how to resolve this, so adding a helpful error message in this case.
Importantly the function jumps out early in this case, returning 1, so the caller can detect that an error occurred.
> If SOLR config.zip cannot be produced, show useful error message.

- alpaca/Dockerfile
Just found this after poking around.  I fixed it in my local docker-compose.yml, but this'll stop everyone else from having to do it :smiley_cat:
> Update default 3-store URL now that we've removed the nginx layer

- drupal/rootfs/etc/islandora/utilities.sh
Somewhere in the D9 upgrade range, the migrate:import function stopped supporting --group, so we have to be a little more specific here. This is addressed temporarily by https://github.com/Islandora-Devops/isle-dc/pull/248 and I'll go back and fix that once the next set of containers is released.
> migrate:import no longer supports --group function

- karaf/README.md
The convention is listed below, and not above.
> changed sentence structure in Karaf Readme

- tomcat/rootfs/etc/confd/templates/server.xml.tmpl
Make tomcat respect `x-forward` headers where tomcat is behind a reverse proxy.
> Respect X-Forwarded headers in responses.

- fits/Dockerfile
Upgraded to FITS 1.5.5 & FITS SERVLET 1.2.3. Changed to Github for all binary sources. Tested on isle-dc
> Upgrade to FITS 1.5.5

- drupal/rootfs/etc/islandora/utilities.sh
Ticket: https://github.com/Islandora-Devops/isle-dc/issues/305
Currently the ISLE-DC build does not configure solr when the Islandora Starter Site is used. I tracked it down to this function, `configure_islandora_default_module`.
The only thing that the function did was to set the Solr URL and port. 
I first just removed the whole `if` statement, but then decided it would be prudent to at least make sure `search_api` is enabled.
I did not rename the function because I am not sure how to manage the integration between versions of Buildkit and ISLE-DC.  Should we do that?
Tagging @aoelschlager
> Enable solr config even when Defaults is not present.

- solr/Dockerfile
- solr/README.md
This is untested.
I think this would work but I'm still testing it.
> Solr 8.11.2 update

- hypercube/Dockerfile
- hypercube/README.md
This resolves [issues/2190](https://github.com/Islandora/documentation/issues/2190). 
I guess we missed this default when removing the nginx proxy from the fedora container?  :shrug: Not sure why this didn't manifest sooner, but it's easily fixable.
> Update default fcrepo URL for Hypercube to use port 8080

- drupal/Dockerfile
- drupal/rootfs/usr/local/bin/drush
- drupal/tests/ServiceStartsWithBackendMySQL/test.sh
- drupal/tests/ServiceStartsWithBackendPostgreSQL/test.sh
Explicitly encode path to expected location for Drush when installed via composer, as recommended.
https://www.drush.org/12.x/install/
> Drush 12 is no longer compatible with Drush launcher.

- drupal/rootfs/etc/islandora/utilities.sh
- drupal/rootfs/usr/share/drush/Commands/UpdateSettingsCommands.php
This PR addresses a couple Drupal 10 issues.
Drush 12 removed the deprecated `--pipe` flag in https://github.com/drush-ops/drush/pull/5502
Drush 12 is required for Drupal 10.
This PR replaces the pipe flag with `--format=string`
Also pull in changes from https://github.com/Islandora-Devops/isle-site-template/pull/7 so isle-dc gets the correct `reverse_proxy_trusted_headers` settings
> Drupal 10 support

- drupal/rootfs/etc/islandora/utilities.sh
`make starter TAG=2.0.2` results in a solr config for solr v7.
isle-buildkit:2.x uses solr v8.
This PR updates the solr config accordingly.
> Drupal 10 support: Upgrade from solr 7 to solr 8

- hypercube/Dockerfile
Closes https://github.com/Islandora-Devops/isle-dc/issues/298 and https://github.com/Islandora/Crayfish/issues/176 
See https://github.com/Islandora/Crayfish/issues/176  for a detail on the issues related to this.
To troubleshoot, I `docker exec`'d into the hypercube container and tried running tesseract manually, which yielded the proper error
```
curl https://islandora.traefik.me/_flysystem/fedora/2023-10/jpeg-2000.jp2 | tesseract stdin stdout -c tessedit_create_hocr=1 -c hocr_font_info=0
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Error opening data file /usr/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX …
```
> Add english OCR training data

- mariadb/Dockerfile
after upgrading mariadb (when we update to a new buildkit TAG) we sometimes need to run mariadb-upgrade to fix our existing databases. That is not included in the image unless we add mariadb-server-utils.
With this change you should be able to run mariadb-upgrade on your container.
Try to run mariadb-upgrade in your mariadb container with and without this PR.
> add mariadb-server-utils to mariadb image

- .github/workflows/release.yml
When a PR merges into main, this GitHub Action will auto bump the latest version number, and create a tag/release with the bumped version. Version number is incremented using [autotag](https://github.com/pantheon-systems/autotag).
> Bump tag version on merge into main

- .github/workflows/push.yml
- .github/workflows/release.yml
Since the release GitHub action [pushes a new tag in this repo](https://github.com/Islandora-Devops/isle-buildkit/blob/40cf50d8003da06a6359ac4b2f9afc68684fa1ca/.github/workflows/release.yml#L25) as the GitHub Actions bot, the tag pushed is not able to trigger [the push.yml action](https://github.com/Islandora-Devops/isle-buildkit/blob/main/.github/workflows/push.yml) (more info as to why in the docs: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow)
This PR manually triggers the push action upon release.
> Fix autotag triggering tag build

- docker-compose.yml
Having the Matomo volume persist the entire /var/www/matomo directory causes problems when upgrading Matomo. This change should allow us to persist the config directory, which I believe is the only thing that needs to persist. 
With this, when new Matomo images are created with new versions of Matomo, we should only need to run database updates. 
This should prevent this issue: https://github.com/Islandora-Devops/isle-dc/issues/361
> changed matomo volume to only persist config directory

- docker-compose.yml
This reverts https://github.com/Islandora-Devops/isle-buildkit/pull/306 because it looks like that is the recommended way to mount the volume, and the recommended way to do updates is through the web UI
https://hub.docker.com/_/matomo
https://github.com/matomo-org/docker/issues/248
> revert matomo mount changes

- drupal/rootfs/etc/islandora/utilities.sh
With https://github.com/Islandora-Devops/isle-buildkit/pull/317 upgrading to solr 9, we should also update the utilities script to download the solr 9 config from Drupal
> Default to solr 9

- hypercube/rootfs/etc/confd/templates/crayfish_commons.yaml.tmpl
Related GitHub issue:
https://github.com/Islandora/Crayfish/issues/181
From my understanding of Crayfish's UPGRADE.md file, this config key is no longer used and its presence is causing errors with Hypercube.
https://github.com/Islandora/Crayfish/blob/4.x/Hypercube/UPGRADE.md
It looks like the other config changes needed for the upgrade are already in place.
> Remove obsolete Crayfish parameter syn_config.

- code-server/rootfs/etc/confd/conf.d/services.yml.toml
- code-server/rootfs/etc/confd/templates/services.yml.tmpl
Removes the forced twig debug settings when code-server is included. 
Having twig debugging on causes lots of HTML comments in the code, which messes up Views' ability to hide empty fields (https://www.drupal.org/project/drupal/issues/2908634). This means that configuring your solr search results view in the dev environment doesn't hide empty fields so you don't know if it's working until you push the config to production.
This PR removes the automatic enabling of twig debugging from code-server so you can now toggle it on and off as normal through Drupal's settings at /admin/config/development/settings
To test:
- Start a new site using the site template, or other method that includes code-server, and inspect the HTML for twig debug comments
- Test that this can not be turned off at …
> remove hard coded settings for twig debug

- solr/Dockerfile
The build will fail if there is a problem downloading the file, otherwise you can just look for the presence of the downloaded .jar file in the above location.## What does this pull request do?
Adds the [OCR Highlighting](https://github.com/dbmdz/solr-ocrhighlighting) plugin to the Solr image.
The jar is placed in a directory where Solr won't find it unless it is explicitly configured to do so, which Drupal sites that are set up to support Solr and hOCR will do. But otherwise the presence of the .jar in the 
/opt/solr/server/solr/contrib/ocrhighlighting/lib/solr-ocrhighlighting-0.8.6.jar
folder will have no effect.
> Solr: Add OCR Highlight plugin.

- drupal/rootfs/etc/nginx/shared/drupal.defaults.conf
With CSS/JS aggregation enabled in Drupal 10, nginx needs to first check if the CSS/JS exists on disk. If not, needs to forward the request to Drupal/php
Using `ISLANDORA_TAG=3.2` see that when CSS/JS aggregation is enabled in your Drupal stack, your theme's page displays are broken
Using this PR's tag `ISLANDORA_TAG=d10-css-js-aggregations` see that CSS/JS aggregation works as expected
https://islandora.slack.com/archives/C019U12D44Q/p1717446855079619?thread_ts=1699377978.424099&cid=C019U12D44Q
> Add Drupal 10+ CSS/JS Aggregation support

- drupal/rootfs/etc/islandora/utilities.sh
Redirecting the output to /dev/null doesn't let us know if the creation of the core failed. This was the issue at https://github.com/Islandora-Devops/isle-buildkit/issues/339
Letting it output the results from Solr will show whether it worked or not when you try to regenerate a new core.
> stop redirecting output to /dev/null when creating solr core

- drupal/rootfs/etc/islandora/utilities.sh
This should fix the issue introduced by drush 13 that stopped us from running certain drush commands before the site was installed. See https://github.com/Islandora-Devops/isle-site-template/pull/58 for more details.
AFAIK the drupal root is always the same when running buildkit in either Isle-dc or site template so this should be fine. 
To test: 
- build the drupal image in this PR with `docker buildx bake drupal`
- create a new site with Site Template as normal
- change the Dockerfile in Isle Site Template to say `FROM islandora/drupal:local` so that it builds from this image
- build a new Drupal image in the site template
- spin up site using `docker compose --profile dev up -d` as normal
> hard code site root

- fits/Dockerfile
Fixes https://github.com/Islandora-Devops/isle-buildkit/issues/352
> Add dependencies to allow FITS to analyze JP2's

- README.md
- base/Dockerfile
- ci/update-sha.sh
- handle/Dockerfile
- renovate.json
- test/Dockerfile
Since handle required a custom data source I wanted to make sure this will pick up new changes. I tested handle by downgrading the Dockerfile to `9.3.0` and changing the SHA and running renovate, and it properly updated to `9.3.1`. I've since rebased the PR to not downgrade handle
You can see the example PR this will create at https://github.com/joecorall/isle-buildkit/pull/13
> Track s6-overlay, handle, and islandora-starter-site with renovate

- activemq/README.md
- alpaca/README.md
- base/README.md
- blazegraph/README.md
- cantaloupe/README.md
- code-server/README.md
- crayfish/README.md
- crayfits/README.md
- drupal/README.md
- fcrepo6/README.md
- fits/README.md
- handle/README.md
- homarus/README.md
- houdini/README.md
- hypercube/README.md
- java/README.md
- mariadb/README.md
- matomo/README.md
- milliner/README.md
- nginx/README.md
- postgresql/README.md
- riprap/README.md
- solr/README.md
- test/README.md
- tomcat/README.md
Aims to make related project visible on image pages at hub.docker.com
~~`sed -i '2 a Docker image for Islandora, built from [Islandora-DevOps/isle-buildkit](https://github.com/Islandora-DevOps/isle-buildkit/)\n' */README.md`~~
~~`sed -Ei '3s@\.([^.]*)$@\1, built from [Islandora-DevOps/isle-buildkit](https://github.com/Islandora-DevOps/isle-buildkit/).@' */README.md`~~
`for ii in */README.md ; do DIR=$( echo $ii | sed -e 's#/README.md##g' ) ; sed -i "4 a Built from [Islandora-DevOps/isle-buildkit $DIR](https://github.com/Islandora-DevOps/isle-buildkit/tree/main/$DIR)\n" $ii ; done`
> Show link to Github project from image READMEs

- .github/workflows/grype.yml
- cantaloupe/rootfs/etc/cont-init.d/01-set-api-secret.sh
- cantaloupe/rootfs/etc/s6-overlay/s6-rc.d/cantaloupe-defaults/type
- cantaloupe/rootfs/etc/s6-overlay/s6-rc.d/cantaloupe-defaults/up
- cantaloupe/rootfs/etc/s6-overlay/scripts/cantaloupe-defaults.sh
- cantaloupe/tests/ServiceHealthcheck/docker-compose.yml
> Healthchecks review

- README.md
- base/Dockerfile
- cantaloupe/Dockerfile
- code-server/Dockerfile
- drupal/Dockerfile
- fits/Dockerfile
- homarus/Dockerfile
- hypercube/Dockerfile
- java/Dockerfile
- mariadb/Dockerfile
- nginx/Dockerfile
- postgresql/Dockerfile
- renovate.json
- riprap/Dockerfile
We can use renovate's [repology datasource ](https://docs.renovatebot.com/modules/datasource/repology/) to update pinned apk packages.
Renovate basically looks for updates at https://pkgs.alpinelinux.org/packages?name=&branch=v3.20 and will bump the respective version in our Dockerfiles along with our other dependency updates. This will give us a little more visibility into what all changes version to version when we cut new releases.
> Pin apk packages

- .github/workflows/release.yml
- .github/workflows/renovate.yml
- README.md
- renovate.json
This PR does four things:
1. When an apk package in isle-buildkit gets an update, auto-merge that if the `test-test/test` CI job succeeds (since we have that set in our branch protection rule as a requirement)
2. Run renovate more often. Previously it was only ran once per week, which was OK when we just checked for dependencies like activemq, composer, etc. But now that package updates are pinned we should get those in sooner than later since a bad pin can break builds
3. Allow running renovate against a PR in this repo. I didn't like that the only way I could easily test changes to our renovate.json was by making changes in the main branch in the repo, so added some config to allow running renovate against a PR
4. Add a new `[skip-release]` option in our PR titles, so the fleet of …
> [skip-release] Automerge apk updates and provide better renovate testing

- .github/workflows/renovate.yml
Follow up of https://github.com/Islandora-Devops/isle-buildkit/pull/385
Not sure where i saw that `--base-branch` flag - looks like it's an environment variable
> [skip-release] fix renovate base branch

- cantaloupe/Dockerfile
Closes https://github.com/Islandora-Devops/isle-buildkit/issues/389
The cantaloupe image was installing libjpeg-turbo with apk, which installs libjpeg-turbo 3.x. However, that library wasn't getting loaded in cantaloupe, so cantaloupe was falling back to `Java2dProcessor` for jpgs
```
Failed to initialize TurboJpegProcessor (error: Can't load library: /opt/libjpeg-turbo/lib/libturbojpeg.so)
```
Once the package was installed properly, we discovered cantaloupe does not work with 3.x. With libjpeg-turbo 3.x installed correctly in cantaloupe it was throwing another error
```
Failed to initialize TurboJpegProcessor (error: 'org.libjpegturbo.turbojpeg.TJScalingFactor[] org.libjpegturbo.turbojpeg.TJ.getScalingFactors()')
```
So I rolled back to `2.0.2` [as the cantaloupe docs …
> Pin libjpegturbo to 2.x

- .github/workflows/release.yml
- renovate.json
Since renovate seems to be tracking our minor/patch bumps pretty well, lets also let it alert us when major updates are available for our dependencies.
The config proposed has renovate open a separate PR for each major update. It also only lets renovate open one major PR bump at a time, and it will list the major updates it has found in https://github.com/Islandora-Devops/isle-buildkit/issues/368 so we can pick and choose which major updates we want to open PRs for.
Also, harden the autotag install we use to bump major/minor/patch versions in this repo https://github.com/Islandora-Devops/isle-buildkit/pull/402/commits/13e814a7fa59f294d7fbe751067426414084e914
> [skip-release] Have renovate track major updates

- activemq/Dockerfile
- blazegraph/Dockerfile
- fits/Dockerfile
- handle/Dockerfile
- renovate.json
- solr/Dockerfile
- tomcat/Dockerfile
Need to prepend `custom.` to the datasource since we're defining [a custom data source manager](https://docs.renovatebot.com/modules/datasource/custom/#usage). We can also simplify handle with this approach.
> [skip-release] correctly reference custom renovate datasources

- renovate.json
exclude repology from weekly updates so their updates can be applied immediately. This is to allow our repology rules, which create a PR immediately when the dependency is discovered, to continue working
> [skip-release] exclude repology from weekly updates

- nginx/rootfs/etc/confd/templates/nginx.conf.tmpl
Since nginx does not include it in its default mime.types file
> [nginx] include mjs mimetype

- .github/workflows/build.yml
As seen in https://github.com/Islandora-Devops/isle-buildkit/pull/420 - using qemu to build multi-platform images takes considerably longer than building for the native CPU architecture. This PR is an attempt to use GitHub's amd+arm runners to build platform-specific images, and a second job to merge those images into a single manifest
> Platform specific runners

- docker-bake.hcl
Rebuild images with `make bake`, after which you can inspect labels with:
```
docker inspect docker.io/islandora/solr:test | jq '.[].Config.Labels'
```
eg testing with my build locally:
```
$ make bake REPOSITORY=xurizaemon TAGS=test TARGET=solr
$ docker inspect docker.io/xurizaemon/solr:test | jq '.[].Config.Labels'
{
"License": "MIT License",
"org.opencontainers.image.source": "https://github.com/Islandora-DevOps/isle-buildkit/",
"org.opencontainers.image.url": "https://github.com/Islandora-DevOps/isle-buildkit/"
}
```
See: [Renovate Docker datasource docs](https://docs.renovatebot.com/modules/datasource/docker/) & [OpenContainers annotations spec](https://github.com/opencontainers/image-spec/blob/main/annotations.md) - hoping to give Renovate a better idea of where to source data. …
> isle-buildkit#377: Add OpenContainers labels to images

- docker-compose.yml
- test/rootfs/etc/s6-overlay/scripts/install.sh
- test/tests/IntegrationTests/docker-compose.yml
As [noted in Slack](https://islandora.slack.com/archives/CM6F4C4VA/p1751663503305519), it would be helpful to use an environment variable name that Drush can actually use for the URI.
> use native drush uri variable

- handle/rootfs/etc/s6-overlay/scripts/process-keys.sh
**Summary**
`process-keys.sh` computes `HANDLE_PUBLICKEY_BASE64` from `pubkey.bin` and persists it into s6’s envdir via `s6-dumpenv`. However, the next step invokes templating through `confd-render-templates.sh` **without** `/command/with-contenv`, so `confd` doesn’t import the freshly written environment. As a result, templates using `{{ getenv "HANDLE_PUBLICKEY_BASE64" }}` (e.g., `siteinfo.json.tmpl`) render an empty `"publicKey.value"`, and the Handle server fails at startup.
**Root cause**
* `s6-env … s6-dumpenv` writes vars to `/var/run/s6/container_environment/…`.
* Only processes launched via `/command/with-contenv …` read/import that envdir.
* `confd-render-templates.sh` was executed without `with-contenv`, so `HANDLE_PUBLICKEY_BASE64` wasn’t visible to `confd`.
**Change**
Prefix …
> s6: run confd under with-contenv so HANDLE_PUBLICKEY_BASE64 is loaded during templating
