Islandora-Devops/isle-buildkit

- nginx/Dockerfile
This is a relatively common dependency for filesystem manipulation- "The functions in this module try to guess the content type and encoding of a file by looking for certain magic byte sequences at specific positions within the file. While this is not a bullet proof approach the heuristics used do a very good job."
> Request: add php7-fileinfo

- matomo/README.md
Only changes to documentation.
https://github.com/Islandora-Devops/isle-buildkit/issues/19
> Updated matomo documentation.

- sandbox/Dockerfile
Resolves https://github.com/Islandora-Devops/isle-buildkit/issues/48
Just a simple directory rename.
> Fixes pdf.js 404

- crayfits/Dockerfile
- crayfits/README.md
- crayfits/rootfs/etc/confd/conf.d/monolog.yaml.toml
- crayfits/rootfs/etc/confd/templates/monolog.yaml.tmpl
- crayfits/rootfs/etc/cont-init.d/03-crayfits-setup.sh
- gemini/README.md
- gemini/rootfs/etc/confd/templates/config.yaml.tmpl
- gemini/rootfs/etc/cont-init.d/03-gemini-setup.sh
- homarus/README.md
- homarus/rootfs/etc/confd/templates/config.yaml.tmpl
- homarus/rootfs/etc/cont-init.d/03-homarus-setup.sh
- houdini/README.md
- houdini/rootfs/etc/cont-init.d/03-houdini-setup.sh
- hypercube/README.md
- hypercube/rootfs/etc/confd/templates/config.yaml.tmpl
- hypercube/rootfs/etc/cont-init.d/03-hypercube-setup.sh
- milliner/README.md
- milliner/rootfs/etc/confd/templates/config.yaml.tmpl
- milliner/rootfs/etc/cont-init.d/03-milliner-setup.sh
- nginx/README.md
- nginx/rootfs/etc/confd/templates/nginx.conf.tmpl
- nginx/rootfs/etc/confd/templates/php-fpm.conf.tmpl
- nginx/rootfs/etc/confd/templates/php.ini.tmpl
- nginx/rootfs/etc/confd/templates/www.conf.tmpl
- nginx/rootfs/etc/cont-init.d/02-fpm-install.sh
- recast/README.md
- recast/rootfs/etc/confd/templates/config.yaml.tmpl
- recast/rootfs/etc/cont-init.d/03-recast-setup.sh
Fixes logging in microservices.
> Fix logging for microservices, now goes to stderr.

- .github/workflows/master.yml
- .github/workflows/push.yml
- README.md
- crayfish/README.md
- fcrepo/rootfs/etc/confd/templates/fcrepo-config.xml.tmpl
- gemini/README.md
- gemini/rootfs/etc/confd/templates/config.yaml.tmpl
- homarus/README.md
- homarus/rootfs/etc/confd/templates/config.yaml.tmpl
- houdini/README.md
- hypercube/README.md
- hypercube/rootfs/etc/confd/templates/config.yaml.tmpl
- milliner/README.md
- milliner/rootfs/etc/confd/templates/config.yaml.tmpl
- recast/README.md
- recast/rootfs/etc/confd/templates/config.yaml.tmpl
Part of https://github.com/Islandora/documentation/issues/1595
> Master -> Main Rename

- .github/workflows/master.yml
- .github/workflows/push.yml
- README.md
- base/Dockerfile
- crayfish/README.md
- fcrepo/rootfs/etc/confd/templates/fcrepo-config.xml.tmpl
- gemini/README.md
- gemini/rootfs/etc/confd/templates/config.yaml.tmpl
- homarus/README.md
- homarus/rootfs/etc/confd/templates/config.yaml.tmpl
- houdini/README.md
- hypercube/README.md
- hypercube/rootfs/etc/confd/templates/config.yaml.tmpl
- java/rootfs/usr/local/bin/install-apache-service.sh
- milliner/README.md
- milliner/rootfs/etc/confd/templates/config.yaml.tmpl
- recast/README.md
- recast/rootfs/etc/confd/templates/config.yaml.tmpl
Looks like main was created from non master branch, so the commits that were in master have not been pulled in? @dannylamb 
Let me know if I should rebase this off main and if the 'main rename' commits need to wait before going into main.
> Fix moved key

- crayfish/Dockerfile
- crayfits/Dockerfile
- demo/Dockerfile
- drupal/rootfs/usr/local/bin/drush
- nginx/Dockerfile
Upgrade to Composer 2.0
**Do not merge until https://github.com/roblib/CrayFits/pull/4** has been merged
Might also wanna hold back on merging this until release pattern is figured out as it could break developers environments if they use the tags `latest` or `0.0.1`.
> Composer 2

- .github/workflows/main.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
Follow up to https://github.com/Islandora-Devops/isle-buildkit/pull/99
With this PR
- Any commit to main updates the `latest` image
- Any version makes images tagged with the versions name/number
- Any commit that's pushed makes images tagged with the commit SHA
> Release versioning

- base/rootfs/etc/cont-init.d/00-container-environment-00-init.sh
Allows kuberentes users to start up the images.
> Temporary fix for Kubernetes

- mariadb/rootfs/etc/cont-init.d/03-mysql-setup.sh
This PR fixes the issue mentioned in #115.
> Fix mariadb root@% password issue

- nginx/Dockerfile
Addresses #141. Just adding another PHP extension which is a dependency for Islandora Bagger, among other things.
> Adds php7-intl

- fcrepo6/Dockerfile
upgrades the version of fedora 6 from beta 1 to release candidate 2
> upgrade fedora 6 to release candidate 2

- fcrepo6/Dockerfile
Follow up to https://github.com/Islandora-Devops/isle-buildkit/pull/147
Adding the corresponding sha256 for the version bump
> Updating SHA256 for fcrepo6 rc 2

- drupal/rootfs/etc/nginx/shared/drupal.defaults.conf
> Allow txt/log files to be served from flysystem.

- .github/workflows/dockerhub-description.yml
Adds Github action to update documentation in DockerHub when main branch is updated and a readme file has been modified.
> Automatically update DockerHub image documentation.

- demo/Dockerfile
- drupal/rootfs/etc/islandora/utilities.sh
Co-authored-by: Rosie Le Faive <lefaive@gmail.com>
Co-authored-by: dannylamb <dlamb@islandora.ca>
> Demo image to use islandora install profile

- imagemagick/build/APKBUILD
To test see the difference between the alpha release and this build.
```bash
docker run --rm -ti -p 8000:8000 islandora/houdini:1.0.0-alpha-16 
```
In a separate shell:
```bash
curl -H "Authorization: Bearer islandora" -H "Apix-Ldp-Resource: http://www.africau.edu/images/default/sample.pdf"  "localhost:8000/identify"
```
Yields:
```bash
sh: gs: not found
convert: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dPrinted=false  '-sOutputFile=/tmp/magick-g6H-TpZRwSZ5ypJX0xXEFYostRKEkiOC%d' '-f/tmp/magick-fisBVcT5FE7CB0x6CG7yQ3_yEJaPdBne' '-f/tmp/magick-yDC4fwTfCG9NYYltgJWJyLGtWveGlIae'' (32512) @ …
```
> Add dependency for gs back into imagemagick

- .vscode/settings.json
- base/Dockerfile
- base/README.md
- base/rootfs/etc/confd/conf.d/cert.pem.toml
- base/rootfs/etc/confd/conf.d/rootCA.pem.toml
- base/rootfs/etc/confd/templates/cert.pem.tmpl
- base/rootfs/etc/confd/templates/rootCA.pem.tmpl
- base/rootfs/etc/cont-init.d/02-cacert-import.sh
> Allow development certificates to be provided as secrets rather than

- fcrepo6/Dockerfile
Changing the fcrepo version and updating the SHA256 hash should bring in the updated WAR.
> Upgrade FCREPO6 to 6.2.0

- crayfits/Dockerfile
- homarus/Dockerfile
- houdini/Dockerfile
- hypercube/Dockerfile
- milliner/Dockerfile
- recast/Dockerfile
- riprap/Dockerfile
All debug log levels changed to info. Less talkative log output per issue #217
> All debug log levels changed to info. Less talkative log output per issue #217

- base/tests/EnvironmentPrecedence/docker-compose.yml
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
> Upgrade Gradle/Plugin to support running tests on M1 macs

- activemq/Dockerfile
- alpaca/Dockerfile
- base/Dockerfile
- blazegraph/Dockerfile
- cantaloupe/Dockerfile
- composer/Dockerfile
- drupal/Dockerfile
- fcrepo/Dockerfile
- fcrepo6/Dockerfile
- fits/Dockerfile
- handle/Dockerfile
- karaf/Dockerfile
- matomo/Dockerfile
- riprap/Dockerfile
- solr/Dockerfile
- tomcat/Dockerfile
No functional change, equivalent to the previous commit, so I'm just gonna push this through.
> Use args for versions, and checksums

- hypercube/Dockerfile
- hypercube/README.md
- hypercube/rootfs/etc/confd/templates/config.yaml.tmpl
> Added hypercube fedora settings back in

- matomo/rootfs/etc/s6-overlay/scripts/install.sh
Resolves #280, pinging @jefferya.
> issue-280 Fix for IP Address forwarding

- activemq/tests/ServiceStartsWithDefaults/build.gradle.kts
- alpaca/tests/ServiceStartsWithDefaults/build.gradle.kts
- cantaloupe/tests/ServiceStartsWithDefaults/build.gradle.kts
- code-server/tests/ServiceStartsWithDefaults/build.gradle.kts
- fcrepo6/tests/ServiceStartsWithBackendFile/build.gradle.kts
- fcrepo6/tests/ServiceStartsWithBackendMySQL/build.gradle.kts
- fcrepo6/tests/ServiceStartsWithBackendPostgreSQL/build.gradle.kts
- fits/tests/ServiceStartsWithDefaults/build.gradle.kts
- tomcat/tests/ServiceStartsWithDefaults/build.gradle.kts
> s6 overlay was updated so no longer need the 143 exit code in tests.

- docker-compose.yml
Update Traefik to 2.11.6. This was tested with the site template (https://github.com/Islandora-Devops/isle-site-template/pull/50) so should not cause any issues.
> Update traefik in docker-compose.yml

- .github/workflows/build.yml
our major/minor/patch tags (e.g. `tags=4.0.15 4.0 4`) need handled when we merge PRs.
> handle multiple tags
